name: Reproduce the v6.31.2 apk files
run-name: ${{ github.actor }} is using GitHub Actions 🚀 to generate the apk packages

permissions:
  contents: read # to fetch code (actions/checkout)

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: v6.31.2

    - name: Show username
      run: whoami

    - name: Show .git owner
      run: ls -al ./

    - name: Show parent folder owner
      run: ls -al ./
      
    - name: Build image
      run: cd reproducible-builds && docker build -t signal-android . && cd ..

    - name: Test build
      run: docker run --rm -v $(pwd):/project -w /project signal-android ./gradlew clean assemblePlayProdRelease
